import style from "./CarLayoutSeatingPosition.module.css"

export function CarLayoutSeatingPosition (){
    return <div className={style.carlayout}>
        <div className={style.plase}>1</div>
        <div className={style.plase}>2</div>
        <div className={style.plase}>3</div>
        <div className={style.plase}>4</div>
        <div className={style.plase}>5</div>
        <div className={style.plase}>6</div>
        <div className={style.plase}>7</div>
        <div className={style.plase}>8</div>
        <div className={style.plase}>9</div>
        <div className={style.plase}>10</div>
        <div className={style.plase}>11</div>
        <div className={style.plase}>12</div>
        <div className={style.plase}>13</div>
        <div className={style.plase}>14</div>
        <div className={style.plase}>15</div>
        <div className={style.plase}>16</div>
        <div className={style.plase}>17</div>
        <div className={style.plase}>18</div>
        <div className={style.plase}>19</div>
        <div className={style.plase}>20</div>
        <div className={style.plase}>21</div>
        <div className={style.plase}>22</div>
        <div className={style.plase}>23</div>
        <div className={style.plase}>24</div>
        <div className={style.plase}>25</div>
        <div className={style.plase}>26</div>
        <div className={style.plase}>27</div>
        <div className={style.plase}>28</div>
        <div className={style.plase}>29</div>
        <div className={style.plase}>30</div>
        <div className={style.plase}>31</div>
        <div className={style.plase}>32</div>
        <div className={style.plase}>33</div>
        <div className={style.plase}>34</div>
        <div className={style.plase}>35</div>
        <div className={style.plase}>36</div>
        <div className={style.plase}>37</div>
        <div className={style.plase}>38</div>
        <div className={style.plase}>39</div>
        <div className={style.plase}>40</div>
        <div className={style.plase}>41</div>
        <div className={style.plase}>42</div>
        <div className={style.plase}>43</div>
        <div className={style.plase}>44</div>
        <div className={style.plase}>45</div>
        <div className={style.plase}>46</div>
        <div className={style.plase}>47</div>
        <div className={style.plase}>48</div>
        <div className={style.plase}>49</div>
        <div className={style.plase}>50</div>
        <div className={style.plase}>51</div>
        <div className={style.plase}>52</div>
        <div className={style.plase}>53</div>
        <div className={style.plase}>54</div>
        <div className={style.plase}>55</div>
        <div className={style.plase}>56</div>
        <div className={style.plase}>57</div>
        <div className={style.plase}>58</div>
        <div className={style.plase}>59</div>
        <div className={style.plase}>60</div>
        <div className={style.plase}>61</div>
        <div className={style.plase}>62</div>
    </div>
}