export const filterSettings = {
    from_city_id : '',
    from_city_name : '',
    to_city_id : '',
    to_city_name : '',
    date_start : '', 
    date_end : '',
    date_start_arrival : '',
    date_end_arrival : '',
    have_first_class : false,
    have_second_class : false,
    have_third_class : false,
    have_fourth_class : false,
    have_wifi : false,
    have_air_conditioning : false,
    have_express : false,
    price_from : '',
    price_to : '',
    start_departure_hour_from : '',
    start_departure_hour_to : '',
    start_arrival_hour_from : '',
    start_arrival_hour_to : '',
    end_departure_hour_from : '',
    end_departure_hour_to : '',
    end_arrival_hour_from : '',
    end_arrival_hour_to : '',
    limit: '',
    offset: '',
    sort : ''
}

export const filterSeatsSettings  = {
    id : '',
    have_first_class : false,
    have_second_class : false,
    have_third_class : false,
    have_fourth_class : false,
    have_wifi : false,
    have_air_conditioning : false,
    have_express : false,
}